export const DEMO = "DEMO";

export const OPEN_PAYMENT = "OPEN_PAYMENT";
export const CLOSE_PAYMENT = "CLOSE_PAYMENT";
export const OPEN_MAIL = "OPEN_MAIL";
export const CLOSE_MAIL = "CLOSE_MAIL";
export const USER_SETTINGS = "USER_SETTINGS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";


export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const RESET_ADD_PRODUCT = "RESET_ADD_PRODUCT";
export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID";
export const PRODUCT_FAILED = "PRODUCT_FAILED";

export const FETCH_CHECKOUTS = "FETCH_CHECKOUTS";
export const ADD_CHECKOUT = "ADD_CHECKOUT";
export const CHECKOUT_PAYMENT = "CHECKOUT_PAYMENT";
export const UPDATE_CHECKOUT = "UPDATE_CHECKOUT";
export const RESET_ADD_CHECKOUT = "RESET_ADD_CHECKOUT";
export const FETCH_CHECKOUT_BY_ID = "FETCH_CHECKOUT_BY_ID";
export const CHECKOUT_FAILED = "CHECKOUT_FAILED";

export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const RESET_ADD_CUSTOMER = "RESET_ADD_CUSTOMER";
export const RESET_ALL_PRODUCT_STATE = 'RESET_ALL_PRODUCT_STATE';
export const RESET_ALL_CUSTOMER_STATE = 'RESET_ALL_CUSTOMER_STATE';
export const FETCH_CUSTOMER_BY_ID = "FETCH_CUSTOMER_BY_ID";
export const CUSTOMER_FAILED = "CUSTOMER_FAILED";

export const SET_COUNTRY = "SET_COUNTRY";
export const SET_STATES = "SET_STATES";
export const RESET_STATES = "RESET_STATES";
export const SET_STATES_FOR_SHIPPING = 'SET_STATES_FOR_SHIPPING';
export const FETCH_COUNTRY_CURRENCY_LIST = "FETCH_COUNTRY_CURRENCY_LIST";
export const FETCH_BUSINESS = "FETCH_BUSINESS";
export const SELECTED_BUSINESS = "SELECTED_BUSINESS";
export const BUSINESS_FAILED = "BUSINESS_FAILED";

export const FETCH_ESTIMATES = "FETCH_ESTIMATES";
export const ADD_ESTIMATE = "ADD_ESTIMATE";
export const RESET_ADD_ESTIMATE = "RESET_ADD_ESTIMATE";
export const FETCH_ESTIMATE_BY_ID = "FETCH_ESTIMATE_BY_ID";
export const ESTIMATE_FAILED = "ESTIMATE_FAILED";


export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const UPDATE_DATA = 'UPDATE_DATA';

export const FETCH_PAYMENT_STATE = 'FETCH_PAYMENT_STATE';
export const ADD_PAYMENT_LOADING = 'ADD_PAYMENT_LOADING';
export const ADD_BUSINESS_TYPE_ONBOARDING = 'ADD_BUSINESS_TYPE_ONBOARDING';
export const ADD_BUSINESS_DETAIL_ONBOARDING = 'ADD_BUSINESS_DETAIL_ONBOARDING';
export const ADD_YOUR_DETAIL_ONBOARDING = 'ADD_YOUR_DETAIL_ONBOARDING';
export const ADD_BANK_DETAIL_ONBOARDING = 'ADD_BANK_DETAIL_ONBOARDING';
export const ADD_CUSTOMIZED_STATEMENT_ONBOARDING = 'ADD_CUSTOMIZED_STATEMENT_ONBOARDING';
export const VERIFY_ONBOARDING = 'VERIFY_ONBOARDING';
export const VERIFY_ONBOARDING_ERROR = 'VERIFY_ONBOARDING_ERROR';

export const GET_ALL_PAYMENT_RECORDS = 'GET_ALL_PAYMENT_RECORDS';
export const GET_PAYMENT_INTERMEDIATE_DATA = 'GET_PAYMENT_INTERMEDIATE_DATA';
export const GET_ALL_REFUND_RECORDS = 'GET_ALL_REFUND_RECORDS';
export const POST_REFUND = 'POST_REFUND';

export const GET_PAYMENT_BY_ID = 'GET_PAYMENT_BY_ID';
export const GET_REFUND_BY_ID = 'GET_REFUND_BY_ID';
export const GET_REFUND_BY_PAYMENT_ID = 'GET_REFUND_BY_PAYMENT_ID';
export const FETCH_CUSTOMER_STATEMENTS = "FETCH_CUSTOMER_STATEMENTS";

export const UPDATE_USER = 'UPDATE_USER';
export const CHANGE_PASS = 'CHANGE_PASS';

export const GET_ALL_VENDORS_SUCESS = 'GET_ALL_VENDORS_SUCCESS';
export const GET_ALL_VENDORS_LOADING = 'GET_ALL_VENDORS_LOADING';
export const GET_ALL_VENDORS_ERROR = 'GET_ALL_VENDORS_ERROR';

export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS';
export const ADD_VENDOR_LOADING = 'ADD_VENDOR_LOADING';
export const ADD_VENDOR_ERROR = 'ADD_VENDOR_ERROR';

export const UPDATE_VENDOR_SUCCESS = 'UPDATE_VENDOR_SUCCESS';
export const UPDATE_VENDOR_LOADING = 'UPDATE_VENDOR_LOADING';
export const UPDATE_VENDOR_ERROR = 'UPDATE_VENDOR_ERROR';

export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const DELETE_VENDOR_LOADING = 'DELETE_VENDOR_LOADING';
export const DELETE_VENDOR_ERROR = 'DELETE_VENDOR_ERROR';

export const GET_BY_ID_VENDOR_SUCCESS = 'GET_BY_ID_VENDOR_SUCCESS';
export const GET_BY_ID_VENDOR_LOADING = 'GET_BY_ID_VENDOR_LOADING';
export const GET_BY_ID_VENDOR_ERROR = 'GET_BY_ID_VENDOR_ERROR';

export const GET_BY_ID_VENDOR_BANK_SUCCESS = 'GET_BY_ID_VENDOR_BANK_SUCCESS';
export const GET_BY_ID_VENDOR_BANK_LOADING = 'GET_BY_ID_VENDOR_BANK_LOADING';
export const GET_BY_ID_VENDOR_BANK_ERROR = 'GET_BY_ID_VENDOR_BANK_ERROR';

export const UPDATE_VENDOR_BANK_SUCCESS = 'UPDATE_VENDOR_BANK_SUCCESS';
export const UPDATE_VENDOR_BANK_LOADING = 'UPDATE_VENDOR_BANK_LOADING';
export const UPDATE_VENDOR_BANK_ERROR = 'UPDATE_VENDOR_BANK_ERROR';

export const SENDMAIL_SUCCESS = 'SENDMAIL_SUCCESS';
export const SENDMAIL_LOADING = 'SENDMAIL_LOADING';
export const SENDMAIL_ERROR = 'SENDMAIL_ERROR';

export const GET_ALL_ACCOUNTS_SUCCESS = 'GET_ALL_ACCOUNTS_SUCCESS';
export const GET_ALL_ACCOUNTS_LOADING = 'GET_ALL_ACCOUNTS_LOADING';
export const GET_ALL_ACCOUNTS_ERROR = 'GET_ALL_ACCOUNTS_ERROR';

export const GET_ALL_INVOICE_PAYMENTS_SUCCESS = 'GET_ALL_INVOICE_PAYMENTS_SUCCESS';
export const GET_ALL_INVOICE_PAYMENTS_LOADING = 'GET_ALL_INVOICE_PAYMENTS_LOADING';
export const GET_ALL_INVOICE_PAYMENTS_ERROR = 'GET_ALL_INVOICE_PAYMENTS_ERROR';

export const GET_ALL_CUSTOMER_CARDS_SUCCESS = 'GET_ALL_CUSTOMER_CARDS_SUCCESS';
export const GET_ALL_CUSTOMER_CARDS_LOADING = 'GET_ALL_CUSTOMER_CARDS_LOADING';
export const GET_ALL_CUSTOMER_CARDS_ERROR = 'GET_ALL_CUSTOMER_CARDS_ERROR';

export const DELETE_CUSTOMER_CARDS_SUCCESS = 'DELETE_CUSTOMER_CARDS_SUCCESS';
export const DELETE_CUSTOMER_CARDS_LOADING = 'DELETE_CUSTOMER_CARDS_LOADING';
export const DELETE_CUSTOMER_CARDS_ERROR = 'DELETE_CUSTOMER_CARDS_ERROR';

export const GET_RECEIPT_SETTINGS_SUCCESS = 'GET_RECEIPT_SETTINGS_SUCCESS';
export const SET_RECEIPT_SETTINGS_SUCCESS = 'SET_RECEIPT_SETTINGS_SUCCESS';
export const SET_RECEIPT_SETTINGS_LOADING = 'SET_RECEIPT_SETTINGS_LOADING';

export const GET_PAYMENT_SETTINGS_SUCCESS = 'GET_PAYMENT_SETTINGS_SUCCESS';
export const SET_PAYMENT_SETTINGS_SUCCESS = 'SET_PAYMENT_SETTINGS_SUCCESS';
export const SET_PAYMENT_SETTINGS_LOADING = 'SET_PAYMENT_SETTINGS_LOADING';

export const GET_ALL_BILLS_LOADING = 'GET_ALL_BILLS_LOADING';
export const GET_ALL_BILLS_SUCCESS = 'GET_ALL_BILLS_SUCCESS';
export const GET_ALL_BILLS_ERROR = 'GET_ALL_BILLS_ERROR';

export const GET_BILL_BY_ID_LOADING = 'GET_BILL_BY_ID_LOADING';
export const GET_BILL_BY_ID_SUCCESS = 'GET_BILL_BY_ID_SUCCESS';
export const GET_BILL_BY_ID_ERROR = 'GET_BILL_BY_ID_ERROR';

export const UPLOAD_RECEIPT_SUCCESS = 'UPLOAD_RECEIPT_SUCCESS';
export const UPLOAD_RECEIPT_LOADING = 'UPLOAD_RECEIPT_LOADING';
export const UPLOAD_RECEIPT_ERROR = 'UPLOAD_RECEIPT_ERROR';
export const UPLOAD_RECEIPT_PROGRESS = 'UPLOAD_RECEIPT_PROGRESS';

export const LIST_RECEIPTS_SUCCESS = 'LIST_RECEIPTS_SUCCESS';
export const LIST_RECEIPTS_LOADING = 'LIST_RECEIPTS_LOADING';
export const LIST_RECEIPTS_ERROR = 'LIST_RECEIPTS_ERROR';

export const UPDATE_RECEIPT_LOADING = 'UPDATE_RECEIPT_LOADING';

export const GET_ALL_RECURRING_SUCCESS = 'GET_ALL_RECURRING_SUCCESS';
export const GET_ALL_RECURRING_LOADING = 'GET_ALL_RECURRING_LOADING';
export const GET_ALL_RECURRING_ERROR = 'GET_ALL_RECURRING_ERROR';

export const GET_ALL_RECURRING_COUNT_SUCCESS = 'GET_ALL_RECURRING_COUNT_SUCCESS';
export const GET_ALL_RECURRING_COUNT_LOADING = 'GET_ALL_RECURRING_COUNT_LOADING';
export const GET_ALL_RECURRING_COUNT_ERROR = 'GET_ALL_RECURRING_COUNT_ERROR';


export const GENERATE_RESET_LINK_SUCCESS = 'GENERATE_RESET_LINK_SUCCESS';
export const GENERATE_RESET_LINK_LOADING = 'GENERATE_RESET_LINK_LOADING';
export const GENERATE_RESET_LINK_ERROR = 'GENERATE_RESET_LINK_ERROR';


export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const VERIFY_LINK_SUCCESS = 'VERIFY_LINK_SUCCESS';
export const VERIFY_LINK_LOADING = 'VERIFY_LINK_LOADING';
export const VERIFY_LINK_ERROR = 'VERIFY_LINK_ERROR';

export const CHARGE_CARD_SUCCESS = 'CHARGE_CARD_SUCCESS';
export const CHARGE_CARD_LOADING = 'CHARGE_CARD_LOADING';
export const CHARGE_CARD_ERROR = 'CHARGE_CARD_ERROR';